FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install libbz2-dev -y
RUN apt-get install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
  libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev \
  liblzma-dev python-openssl git libuv1-dev python3-virtualenv virtualenv python3-dev -y


# Isolate system python packages from those used in project
RUN virtualenv --python=python3 /venv
RUN mkdir /src

WORKDIR /src
COPY hitch/hitchreqs.txt /
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
RUN /venv/bin/pip install setuptools-rust
RUN /venv/bin/pip install -r /hitchreqs.txt
